### ISSUE TITLE
My players cannot sleep in homedecor beds after 0.4.16

### ISSUE THREAD

**Issue by redblade7** [minetest-mods/homedecor_modpack#367] opened 2017-06-04 19:24 UTC
After upgrading my server to 0.4.16 and this mod, players are unable to sleep in homedecor's beds. Right-clicking on the bed does nothing. The built-in beds work fine. I'm sure very shortly players will  start getting angry and leave.

**Comment by paramat** [comment] 2017-06-04 19:55
IRC discussion http://irc.minetest.net/minetest/2017-06-04#i_4959129

**Comment by bell07** [comment] 2017-06-06 20:17
Can anyone provide more informations about the crash in mtg that was fixed by https://github.com/minetest-mods/homedecor_modpack/commit/3969f1a19836300e723c1bf379f3df6ddfc77989?
I re-enabled the sleeping and no crash was happened. Some strange behaviour like the player lay besides and crosswise the bed and the collision-box seems does not work proper, but no crash that show me the code place of the issue.

**Comment by VanessaE** [comment] 2017-06-06 23:46
Unfortunately, I don't have anything in my chat logs or server logs going that far back, and I don't remember what the nature of the crash was.  Maybe try rolling minetest, mt_game, and homedecor to just before the date of that commit, and see if you can crash it then?

For some reason, I keep thinking it has to do with trying to sleep not in a regular bed, but in either a king-sized bed, or maybe in a "bunk" bed.

**Comment by AntumDeluge** [comment] 2017-06-11 01:24
I've created a [branch that re-enables sleeping](https://github.com/AntumDeluge/mtmp-homedecor/tree/enable_sleep) if anyone wants to use it for now. I haven't had any crashes caused by it so far. But, I have not tried sleeping in a "bunk" bed, like @VanessaE was saying.

**Comment by VanessaE** [comment] 2017-06-15 18:02
@AntumDeluge  were you able to reproduce the crash at all?  I'm not too worried about the players sinking through those other beds (and I don't have the faintest clue why it happens).

**Comment by AntumDeluge** [comment] 2017-06-16 02:58
No, haven't had any crashes yet. But so far have only tested on singleplayer.

**Comment by VanessaE** [comment] 2017-06-16 18:40
Ok, sounds good to me.  The problem of sinking through a bed can be dealt with some other time.  Pushed 43f3cf08055603c05f7f23a6071e482641e9f4f2 (your two commits, squashed).

**Comment by redblade7** [comment] 2017-06-17 04:15
Sleeping in certain colors of beds (dark green, dark gray, green, magenta, pink) crash the server with:

2017-06-16 23:57:40: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback item_OnPlace(): [removed]/games/minetest_game/mods/beds/functions.lua:90: attempt to index local 'dir' (a nil value)
2017-06-16 23:57:40: ERROR[Main]: stack traceback:
2017-06-16 23:57:40: ERROR[Main]:       [removed]/games/minetest_game/mods/beds/functions.lua:90: in function 'lay_down'
2017-06-16 23:57:40: ERROR[Main]:       [removed]/games/minetest_game/mods/beds/functions.lua:150: in function 'on_rightclick'
2017-06-16 23:57:40: ERROR[Main]:      [removed]/mods/homedecor_modpack/homedecor/bedroom.lua:146: in function 'on_rightclick'
2017-06-16 23:57:40: ERROR[Main]:       [removed]/builtin/game/item.lua:347: in function [removed]/builtin/game/item.lua:340

**Comment by AntumDeluge** [comment] 2017-06-17 04:29
Interesting. I didn't try colored beds. I'll test that as well when I get time.

**Comment by VanessaE** [comment] 2017-06-17 04:33
@paramat   looks like a minetest_game bug.  All my mod passes to the beds code is position and clicker:
```lua
	on_rightclick = function(pos, node, clicker, itemstack, pointed_thing)
		local itemname = itemstack:get_name()
		if itemname == "homedecor:bed_regular" then
			homedecor.bed_expansion(pos, clicker, itemstack, pointed_thing, true)
			return itemstack
		else
			if minetest.get_modpath("beds") then
				beds.on_rightclick(pos, clicker) -- <----- here
			end
			return itemstack
		end
		return itemstack
	end
```

**Comment by VanessaE** [comment] 2017-06-17 04:38
@paramat  I have to wonder if this crash is because homedecor's beds are "fake wallmounted" (and so facedir works differently for them):

This code doesn't look like it's meant to deal with anything but plain facedir:   https://github.com/minetest/minetest_game/blob/master/mods/beds/functions.lua#L87-L90

**Comment by paramat** [comment] 2017-06-17 19:40
'Wallmounted' uses different values to 'facedir' for the 6 'wallmounted' rotations.

**Comment by paramat** [comment] 2017-06-17 19:51
Your beds use colorwallmounted? What is 'fake wallmounted'?
If `dir` is nil then `minetest.facedir_to_dir(param2)` is failing, and param2 is the param2 of the bed node at 'bed_pos' from `function get_look_yaw(pos)`.
Because this happens with certain colour beds i suspect some colour beds have param2 values that exceed the limits of 'facedir'.

**Comment by paramat** [comment] 2017-06-17 19:59
The beds code should probably strip away the colour bits in 'colormounted' but otherwise it is up to your mod to have beds with compatible param2, it's not the responsibility of MTG.

**Comment by VanessaE** [comment] 2017-06-17 20:04
The reason for "fake wallmounted" is simple.  Imagine a default sign:  it can hang on any of the four cardinal direction walls, as well as flat on the ground or ceiling.  The latter two have exactly one orientation each - the sign cannot be rotated, it can only be moved to one of the other 5 faces.

Now imagine a node with `paramtype2 = "wallmounted"` in the node definition, but with its model designed such that a `param2`value that should place it on a wall, actually makes the model look like it's on the floor, facing one of the four X/Z directions... i.e. the vertical surface that is the head of the bed is against the wall, is if it were a sign.

Now extend that to "colorwallmounted" and you get the four-direction effect, with 32 colors available in the upper (color) bits of param2.

The code in minetest_game should strip out the color bits, and probably should allow a mod to pass a custom param2 value to it, that way Home Decor can calculate the correct player orientation and pass that along to the beds code.

**Comment by VanessaE** [comment] 2017-06-17 20:07
If I had used `paramtype2 = "facedir"` (or '"colorfacedir"`), only 8 colors would be available for param2 coloring.  In the past, there used to be a dozen or so beds, each in a different color, using plain old facedir and colors baked into the textures (i.e. no param2 coloring support).

**Comment by paramat** [comment] 2017-06-17 20:09
I see, clever.

**Comment by paramat** [comment] 2017-06-17 20:12
Seems reasonable, the code could detect if 'colorwallmounted' is being used and remove bits accordingly. It needs to do this anyway for 'colorfacedir'.

**Comment by hdak1945git** [comment] 2017-07-01 20:58
This might be out of hand since I'm not really familiar with minetest modding, nor how the homedecor and unified dyes mods interact. But after looking around I have to ask: why aren't the meta functions (e.g. [minetest.get_meta(pos)](http://dev.minetest.net/minetest.get_meta) ) used to store/retrieve color information? The documentation I managed to find on [nodes](http://dev.minetest.net/node) seems to imply `param2` and friends are engine reserved variables.

The `metadata:get_int(..)` function would give you much more than 256 colors too (unless the C++ code redefined `int`).

**Comment by VanessaE** [comment] 2017-07-01 22:26
I believe I suggested that very thing a long time ago, but the idea was rejected because node metadata is somewhat heavy compared to param2, and every node in the map already has a param2 value (one byte, along with a one-byte param1 and a two-byte node ID), so no extra storage is needed.

**Comment by hdak1945git** [comment] 2017-07-02 02:15
I managed to hack myself a solution, though incomplete as it is (as you still fall through the bed when sleeping) it'll work for my small group of players.

This [patch](https://gist.github.com/hdak1945git/f0d4868d82a6c1584f7e9c1c186593b4) is for `minetest_game` itself (to prevent bed colors from being simply being toggled). Apply it in the directory for `functions.lua` (Located on Arch Linux in `/usr/share/minetest/games/minetest/mods/beds`) using simply `patch < bed-homedecor-workaround.patch` Restarting your server if need be.
 
I'm still in favor of using metadata for this sort of thing, but given the revelation that Lua (at least in Minetest) doesn't even support [bitwise operators](https://github.com/minetest/minetest/issues/3028) I'll have to reserve my judgment on this.

**Comment by VanessaE** [comment] 2017-07-02 02:26
Better you should file that as a pull request against minetest_game.  There's already an issue for the crash bug, https://github.com/minetest/minetest_game/issues/1784  so you might want to key in, there.

**Comment by redblade7** [comment] 2017-09-23 23:00
I notice that you cannot dye the beds with certain colors like chartreuse, pastel, etc. As a workaround, is it possible for me to prevent players from dying beds with the 5 colors mentioned above?

**Comment by VanessaE** [comment] 2017-09-23 23:28
I will not be doing that.  The underlying problem needs fixed in minetest_game.

**Comment by redblade7** [comment] 2017-09-23 23:38
No, just as a workaround for me right now I mean.

**Comment by VanessaE** [comment] 2017-09-24 00:19
Sorry, but no.  I'm not doing any coding right now.

**Comment by redblade7** [comment] 2017-09-24 06:22
The warning comes from unifieddyes, not homedecor. Never mind, I thought there was an "if" somewhere that I could add to.

Guess I gotta wait for 0.4.17...

**Comment by VanessaE** [comment] 2017-09-29 05:05
4eaf265e658366c8893398dc132c44b5ebed6b02

**Closed by VanessaE** 2017-09-29 05:05 UTC
